name: sauce_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_custom_bottom_tab_bar:
#    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar.git
  flutter_swiper: ^1.0.6
  dio: ^2.2.2
  flutter_easyrefresh: ^2.0.2
  json_serializable: ^2.0.0 # 解析
  transparent_image: ^0.1.0
  build_runner: ^1.1.2 # 解析
  fluttertoast: ^3.1.0
  flutter_screenutil: ^0.5.3
  flare_flutter: ^1.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  video_player: ^0.7.2
  qrcode_reader: ^0.4.4
  chewie:
    git: https://github.com/brianegan/chewie.git
  city_pickers: ^0.0.1
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  path_provider: ^0.4.1
  #  cached_network_image:
  #    git: https://github.com/tangtaoit/flutter_cached_network_image.git
  photo_view: ^0.4.2
  fake_tencent:
    git:
      url: https://github.com/v7lin/fake_tencent.git
  fluwx: ^1.0.4
  flutter_tags: ^0.4.3
  jmessage_flutter: ^0.2.0
  jpush_flutter:
    git: https://github.com/jpush/jpush-flutter-plugin.git
  tobias: ^1.1.0+1
  flutter_marquee:
    git: https://github.com/LiuC520/flutter_marquee.git
  ripple_backdrop_animate_route: ^0.1.2
  flutter_webview_plugin: ^0.2.1+2
  image_picker: ^0.4.12+1
  flutter_luban: ^0.1.1
  shared_preferences: ^0.4.3
#  amap_base: ^0.3.1
  dropdown_menu: ^1.1.0
  keyboard_visibility: ^0.5.2
  event_bus: ^1.1.0
  share: ^0.6.1+1
  uuid: 2.0.1
  intl: ^0.15.6
  flutter_bugly: ^0.1.1
  photo: ^0.4.3+1
  amap_location: 0.1.0
  crypto: ^2.1.3
  simple_permissions:
dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assert/imgs/ic_shop_car.png
    - assert/imgs/ic_user_boy.png
    - assert/imgs/ic_user_girl.png
    - assert/imgs/ic_back.png
    - assert/imgs/detail_like_selectedx.png
    - assert/amap/
    - assert/imgs/
    - assert/imgs/post_add_img.png
    - assert/imgs/user_address_editor.png
    - assert/imgs/ic_location_receive.png
    - assert/imgs/ic_user_location.png
    - assert/imgs/img_arrow.png
    - assert/imgs/tabbar_project_normal.png
    - assert/imgs/manx.png
    - assert/imgs/ic_game_lol.png
    - assert/imgs/near_a.png
    - assert/flare/Space.flr
    - assert/imgs/ic_empty_bg.png
    - assert/imgs/ic_shopcar.png
    - assert/json/country_code_json.json
    - assert/imgs/tabbar_project_selected.png
    - assert/imgs/tabbar_home_normal.png
    - assert/imgs/message_like.png
    - assert/imgs/message_chat.png
    - assert/imgs/tapbar_home_selected.png
    - assert/imgs/tabbar_person_normal.png
    - assert/imgs/ic_add_normal.png
    - assert/imgs/tabbar_message_normal.png
    - assert/imgs/tabbar_message_selected.png
    - assert/imgs/ic_common_back.png
    - assert/imgs/loading.gif
    - assert/imgs/login_arrow_rightx.png
    - assert/imgs/closex.png
    - assert/imgs/ic_ranting_select.png
    - assert/imgs/ic_ranting_unselect.png
    - assert/imgs/ic_shop_home.png
    - assert/imgs/ic_log_home.png
    - assert/imgs/ic_active_home.png
    - assert/imgs/ic_partjob_home.png
    - assert/imgs/ic_online.png
    - assert/imgs/ic_game_home.png
    - assert/imgs/person_arrow_downx.png
    - assert/imgs/login_qq.png
    - assert/imgs/login_wechat.png
    - assert/imgs/icon_activity.png
    - assert/imgs/icon_comment.png
    - assert/imgs/icon_emoticon.png
    - assert/imgs/icon_label.png
    - assert/imgs/message_reply_arrow_right.png
    - assert/imgs/message_notice_arrow_right.png
    - assert/imgs/message_chat_arrow_right.png
    - assert/imgs/person_arrow_right_grayx.png
    - assert/imgs/message_thumb_arrow_right.png
    - assert/imgs/message_notice.png
    - assert/imgs/ic_square_add_user.png
    - assert/imgs/ic_square_search.png
    - assert/imgs/message_reply.png
    - assert/imgs/ic_photo.png
    - assert/imgs/tabbar_person_selected.png
    - assert/imgs/center_circle.png
    - assert/imgs/ic_user_collection.png
    - assert/imgs/ic_user_invite.png
    - assert/imgs/ic_user_post_collection.png
    - assert/imgs/ic_user_prize.png
    - assert/imgs/video_player.png
    - assert/imgs/ic_user_setting.png
    - assert/imgs/ic_user_view_history.png
    - assert/imgs/person_morex.png
    - assert/imgs/person_likex.png
    - assert/imgs/post_more.png
    - assert/imgs/person_share.png
    - assert/imgs/person_commentx.png
    - assert/imgs/part_time_job_alert.png
    - assert/imgs/part_job_vertify.png
    - assert/imgs/arrow_down_refund.png
    - assert/imgs/icon_image_delete.png
    - assert/imgs/ic_square_picture.png
    - assert/imgs/ic_square_video.png
    - assert/imgs/ic_square_write.png
    - assert/imgs/ic_user_game.png
    - assert/imgs/icon_female.png
    - assert/imgs/icon_male.png
    - assert/imgs/ic_square_scan.png
